; Защита cookie
session.cookie_httponly = 1
session.cookie_secure = 1
session.cookie_samesite = "Lax"

; Время жизни
session.gc_maxlifetime = 1800 ; 30 минут

; Имя cookie (по умолчанию PHPSESSID)
session.name = "SID"

; Предотвращение фиксации ID
session.use_strict_mode = 1

; Генерация ID только на старте
session.use_trans_sid = 0
