CREATE TABLE temp_table1 (
    ID1 INTEGER,
    NAME1 TEXT,
    DESCRIPTION1 TEXT,
    NUM1 REAL,
    IDFROMTABLE2 INTEGER,
    IDFROMTABLE3 INTEGER
);

INSERT INTO temp_table1 (ID1, NAME1, DESCRIPTION1, NUM1, IDFROMTABLE2, IDFROMTABLE3)
SELECT ID1, NAME1, DESCRIPTION1, NUM1, IDFROMTABLE2, IDFROMTABLE3
FROM TABLE1;

DROP TABLE TABLE1;
ALTER TABLE temp_table1 RENAME TO TABLE1;
