name: Сборка и тестирование проекта

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v4
      
      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Установка зависимостей
        run: npm ci
      
      - name: Запуск тестов
        run: npm test
      
      - name: Создание артефакта
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: ./build
