events {}
http {
  upstream front { server frontend:80; }
  upstream back  { server api:5678; }

  server {
    listen 80;
    location /api/ {
      proxy_pass http://back/;
    }
    location / {
      proxy_pass http://front;
    }
  }
}
