spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.example: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.example: WARN

server:
  shutdown: graceful
