SELECT *
FROM TABLE1
WHERE NAME1 LIKE 'A%';

SELECT *
FROM TABLE1
WHERE NUM1 > 10 AND IDFROMTABLE2 = 5;

SELECT *
FROM TABLE1
WHERE NUM1 > 10 OR IDFROMTABLE2 = 5;

SELECT ID1, NAME1,
  CASE
    WHEN NUM1 > 10 THEN 'Большое значение'
    ELSE 'Маленькое значение'
  END AS value_category
FROM TABLE1;
